### ISSUE TITLE
Button instead of slider?

### ISSUE THREAD

**Issue by mrz5018** [pltarun/scale#1]
I have a fork where I added in a button to tare the scale (I did it before you added in the slider).  I just wanted to put it out there and see if you're interested in pulling the change in.  Could add a selector at the bottom where the user selects between tare methods?  Let me know what you think.

https://mrz5018.github.io/scale

I write embedded software mainly, so I was just playing around with my JavaScript knowledge for fun (definitely not a pro).

**Comment by pltarun** [comment]
Your method makes a lot more sense, so I've replaced the slider with it. I originally went with the slider because there would be no way to click a button while placing a weight on the touchpad on Macs, but in retrospect this can be fixed by adding a keyboard shortcut.
