### ISSUE TITLE
 Must have a finger to trigger the touch event

### ISSUE THREAD

**Issue by Robin-front** [pltarun/scale#4]
There are some limitations，Must have a finger to trigger the touch event, if just a cup, not work.
Of course, this is the capacitive screen limitations， right ?

**Comment by pltarun** [comment]
I don't think it's actually an inherent limitation of capacitive pressure transducers, but that's a little out of my depth. We can only use the JavaScript APIs that Apple chooses to make available, so this is not something that we can fix.
